### ISSUE TITLE
Merge bot breaks when you submit an empty commit

### ISSUE THREAD

**Issue by mariuszste** [Limitly/Free-Copilot#113]
## Steps to reproduce

1. create a commit that changes nothing
2. create PR

example failing pr: https://github.com/Limitly/Free-Copilot/pull/111

**Comment by InimicalPart** [comment]
Thanks for the report! I'll look into it and fix it ASAP

**Comment by InimicalPart** [comment]
Should be fixed now :)

**Comment by sudo-do** [comment]
why would anyone pr nothing lol

**Comment by InimicalPart** [comment]
We dropped it because we realized that the repository is active anyway by new people that submit PRs, and we weren't seeing a lot of people actively committing each month, so we dropped it

**Comment by InimicalPart** [comment]
As for empty commits, we want people to upload stuff to their workspace so that it isn't just empty and boring, I'm pretty sure people go around the folders just checking what people have put in their workspace, so it's kinda fun. I know I certainly check what people put in their folders :). 

If you don't have ideas for what to put, you can put information about your recent projects, maybe some code samples as well, you could have a statistics page, and a lot more! The sky's the limit :)

**Comment by sudo-do** [comment]
Github = Unlimited storage (Public)
