### ISSUE TITLE
I am sure no one at GitHub will recognize the purpose of this repository 

### ISSUE THREAD

**Issue by FrankHileman** [Limitly/Free-Copilot#92]
After all, it is not as if the purpose is obvious at first glance 😜

Does anyone really believe this will work?

**Comment by InimicalPart** [comment]
We think that it's based on criteria with no human intervention, of course it could be that a human is deciding which repositories are popular, but we feel like there are so many of them that they have a machine that checks for criterias.

**Comment by issmootype** [comment]
@InimicalPart Suppose there is no human involvement, and this repository has gained popularity, allowing everyone with write access to use Copilot. However, do you believe this situation will persist indefinitely? Once Github staff discovers this repository or someone reports it, the access to Copilot could be revoked for all users. It seems unlikely that Github will condone this repository's existence since it is not providing any genuine value beyond unintended access to Copilot.

**Comment by sudo-do** [comment]
> We think that it's based on criteria with no human intervention

We *sure* as gh support said.

**Comment by sudo-do** [comment]
@FrankHileman See https://github.com/Limitly/Free-Copilot/pull/70
